export const ANALYTICS_EVENT_NAMES = [
  "application_error",
  "application_start",
  "application_submit",
  "landing_view",
  "language_change",
  "lesson_start",
  "lesson_video_complete",
  "lesson_video_progress",
  "lesson_video_start",
  "media_error",
  "next_lesson_open",
  "page_view",
  "practice_fail",
  "practice_pass",
  "practice_retry",
  "practice_start",
  "practice_submit",
  "sample_practice_complete",
  "sample_practice_start",
  "sample_question_answered",
  "signup_click",
  "signup_complete",
  "signup_error",
  "signup_start",
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENT_NAMES)[number];

export type AnalyticsProperties = Record<string, string | number | boolean>;

export const ANALYTICS_PROPERTY_KEYS = new Set([
  "acquisition_source",
  "assignment_id",
  "attempt_number",
  "content_language",
  "correct",
  "error_type",
  "grade_level",
  "lesson_id",
  "media_type",
  "progress_percent",
  "question_count",
  "referrer_domain",
  "role",
  "score_percent",
  "section",
  "source",
  "subject_id",
  "target_language",
  "utm_campaign",
  "utm_medium",
  "utm_source",
]);
