import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const supabase = await createClient();
    
    // Get authenticated user
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Get request body
    const body = await request.json();
    const { code } = body;

    if (!code || typeof code !== "string") {
      return NextResponse.json(
        { error: "Invitation code is required" },
        { status: 400 }
      );
    }

    // Find and validate invite
    const { data: invite, error: inviteError } = await supabase
      .from("guardian_invites")
      .select("*")
      .eq("code", code.toUpperCase().trim())
      .single();

    if (inviteError || !invite) {
      return NextResponse.json(
        { error: "Invalid or expired invitation code" },
        { status: 404 }
      );
    }

    // Check if invite is already used
    if (invite.used_at) {
      return NextResponse.json(
        { error: "This invitation code has already been used" },
        { status: 400 }
      );
    }

    // Check if invite is expired
    const now = new Date();
    const expiresAt = new Date(invite.expires_at);
    if (expiresAt < now) {
      return NextResponse.json(
        { error: "This invitation code has expired" },
        { status: 400 }
      );
    }

    // Prevent student from linking to themselves
    if (invite.student_id === user.id) {
      return NextResponse.json(
        { error: "You cannot link to yourself" },
        { status: 400 }
      );
    }

    // Check if link already exists
    const { data: existingLink } = await supabase
      .from("guardian_students")
      .select("id")
      .eq("guardian_id", user.id)
      .eq("student_id", invite.student_id)
      .single();

    if (existingLink) {
      // Mark invite as used anyway
      await supabase
        .from("guardian_invites")
        .update({ used_at: new Date().toISOString(), used_by: user.id })
        .eq("id", invite.id);

      return NextResponse.json(
        { error: "You are already linked to this student" },
        { status: 400 }
      );
    }

    // Create guardian-student link
    const { data: link, error: linkError } = await supabase
      .from("guardian_students")
      .insert({
        guardian_id: user.id,
        student_id: invite.student_id,
        relationship_type: invite.relationship_type,
        is_approved: true, // Auto-approve since invite was generated by student
      })
      .select("*, profiles!guardian_students_student_id_fkey(id, full_name, email)")
      .single();

    if (linkError) {
      console.error("Error creating guardian link:", linkError);
      return NextResponse.json(
        { error: "Failed to create link" },
        { status: 500 }
      );
    }

    // Mark invite as used
    await supabase
      .from("guardian_invites")
      .update({ used_at: new Date().toISOString(), used_by: user.id })
      .eq("id", invite.id);

    return NextResponse.json({
      success: true,
      student: link.profiles,
      relationshipType: link.relationship_type,
    });
  } catch (error) {
    console.error("Error in POST /api/guardian/link:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
