'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import type { Slide } from '@/lib/slides.types';
import { clampSlideCount, type SlideGenerationContext, type SlideLanguageMode } from '@/lib/slides-generation';

interface SlideGenerateButtonProps {
  lessonId: string;
  hasExistingSlides: boolean;
  onGenerated: (slides: Slide[]) => void;
  languageMode?: SlideLanguageMode;
  generationContext?: SlideGenerationContext | null;
  slideCount?: number;
  autoGenerate?: boolean;
  disabledReason?: string | null;
  onGeneratingChange?: (generating: boolean, progress: string) => void;
  /** When true, only render the button — no inline progress card */
  compact?: boolean;
}

export default function SlideGenerateButton({
  lessonId,
  hasExistingSlides,
  onGenerated,
  languageMode = 'ar',
  generationContext = null,
  slideCount = 10,
  autoGenerate = false,
  disabledReason = null,
  onGeneratingChange,
  compact = false,
}: SlideGenerateButtonProps) {
  const [generating, setGenerating] = useState(false);
  const [progress, setProgress] = useState('');
  const [error, setError] = useState('');
  const hasAutoGenerated = useRef(false);
  const ctaLabel = hasExistingSlides
    ? 'Regenerate Presentation Slides'
    : 'Generate Presentation Slides';

  const tryRecoverSavedSlides = useCallback(
    async (generationStartedAtMs: number): Promise<Slide[] | null> => {
      const maxAttempts = 40;

      setProgress('Checking for saved slides...');
      onGeneratingChange?.(true, 'Checking for saved slides...');

      for (let attempt = 0; attempt < maxAttempts; attempt += 1) {
        await new Promise((resolve) => window.setTimeout(resolve, attempt === 0 ? 2000 : 3000));

        try {
          const res = await fetch(`/api/teacher/lessons/${lessonId}/slides?ts=${Date.now()}`);
          if (!res.ok) {
            continue;
          }

          const data = await res.json();
          const deck = data.slideDeck;
          const updatedAtMs = deck?.updated_at ? Date.parse(deck.updated_at) : Number.NaN;
          const freshEnough =
            Number.isFinite(updatedAtMs) && updatedAtMs >= generationStartedAtMs - 5000;

          if (freshEnough && Array.isArray(deck?.slides) && deck.slides.length > 0) {
            return deck.slides as Slide[];
          }

          if (
            freshEnough &&
            Array.isArray(deck?.slides) &&
            deck.slides.length === 0 &&
            deck?.generated_at
          ) {
            throw new Error('Background generation failed before slides were saved.');
          }
        } catch (error) {
          if (
            error instanceof Error &&
            error.message === 'Background generation failed before slides were saved.'
          ) {
            throw error;
          }
          // Continue polling for a freshly-saved deck.
        }
      }

      return null;
    },
    [lessonId, onGeneratingChange]
  );

  const handleGenerate = useCallback(async () => {
    if (disabledReason) {
      return;
    }

    if (hasExistingSlides) {
      const confirmed = window.confirm(
        'This will replace existing slides. Continue?'
      );
      if (!confirmed) return;
    }

    setGenerating(true);
    setError('');
    const normalizedSlideCount = clampSlideCount(slideCount);
    const generationStartedAtMs = Date.now();
    const progressMsg = `Generating ${normalizedSlideCount} slides...`;
    setProgress(progressMsg);
    onGeneratingChange?.(true, progressMsg);
    let hasPolledBackground = false;

    try {
      const res = await fetch(`/api/teacher/lessons/${lessonId}/slides/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          slide_count: normalizedSlideCount,
          language_mode: languageMode,
          generation_context: generationContext,
        }),
      });

      if (res.status === 202) {
        setProgress('Generation started. Waiting for slides...');
        onGeneratingChange?.(true, 'Generation started. Waiting for slides...');

        hasPolledBackground = true;
        const recoveredSlides = await tryRecoverSavedSlides(generationStartedAtMs);
        if (recoveredSlides) {
          setError('');
          setProgress('Slides loaded.');
          onGenerated(recoveredSlides);
          return;
        }

        throw new Error(
          'No new slides were saved within 2 minutes. Background generation likely failed. Please try again.'
        );
      }

      if (!res.ok) {
        const text = await res.text();
        let errorMessage = 'Generation failed';
        try {
          const data = JSON.parse(text);
          errorMessage = data.error || errorMessage;
        } catch {
          if (res.status === 502 || res.status === 504) {
            errorMessage = 'Generation timed out — the AI call took too long. Please try again.';
          } else {
            errorMessage = `Server error (${res.status})`;
          }
        }
        throw new Error(errorMessage);
      }

      setProgress('Processing...');
      const data = await res.json();
      onGenerated(data.slides || []);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Generation failed';
      const shouldAttemptRecovery =
        !hasPolledBackground &&
        errorMessage.includes('timed out') ||
        !hasPolledBackground &&
        errorMessage.startsWith('Server error') ||
        !hasPolledBackground &&
        errorMessage === 'Generation failed' ||
        !hasPolledBackground &&
        errorMessage.includes('Failed to fetch') ||
        !hasPolledBackground &&
        errorMessage.includes('still running in the background');

      const recoveredSlides = shouldAttemptRecovery
        ? await tryRecoverSavedSlides(generationStartedAtMs)
        : null;
      if (recoveredSlides) {
        setError('');
        setProgress('Slides loaded.');
        onGenerated(recoveredSlides);
        return;
      }

      setError(errorMessage);
    } finally {
      setGenerating(false);
      setProgress('');
      onGeneratingChange?.(false, '');
    }
  }, [disabledReason, generationContext, hasExistingSlides, languageMode, lessonId, onGenerated, onGeneratingChange, slideCount, tryRecoverSavedSlides]);

  useEffect(() => {
    if (!autoGenerate || hasExistingSlides || hasAutoGenerated.current || disabledReason) {
      return;
    }

    hasAutoGenerated.current = true;
    void handleGenerate();
  }, [autoGenerate, disabledReason, handleGenerate, hasExistingSlides]);

  return (
    <div className="space-y-3">
      <button
        type="button"
        onClick={handleGenerate}
        disabled={generating || Boolean(disabledReason)}
        className="px-5 py-2.5 bg-[#007229] text-white rounded-xl text-sm font-medium
                   hover:bg-[#005C22] transition-colors disabled:opacity-50
                   disabled:cursor-not-allowed flex items-center gap-2"
      >
        {generating ? (
          <>
            <svg className="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
            </svg>
            {progress || 'Generating...'}
          </>
        ) : (
          <>
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
            </svg>
            {ctaLabel}
          </>
        )}
      </button>

      {generating && !compact && (
        <div className="border border-emerald-200 bg-emerald-50 rounded-xl p-4 flex items-center gap-3">
          <svg className="animate-spin h-5 w-5 text-emerald-600 flex-shrink-0" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
          <div>
            <p className="text-sm font-medium text-emerald-800">{progress}</p>
            <p className="text-xs text-emerald-600">This usually takes about 1-2 minutes.</p>
          </div>
        </div>
      )}

      {error && !generating && (
        <div className="border border-red-200 bg-red-50 rounded-xl p-3">
          <p className="text-sm text-red-800">{error}</p>
        </div>
      )}

      {disabledReason && !generating && !error && (
        <div className="border border-amber-200 bg-amber-50 rounded-xl p-3">
          <p className="text-sm text-amber-800">{disabledReason}</p>
        </div>
      )}
    </div>
  );
}
