-- =============================================================================
-- Launch-readiness authentication hardening
-- - Never trust a public signup to assign the admin role
-- - Persist parent/volunteer applications from auth metadata at signup time
-- - Add a service-only, hashed signup-attempt log for WhatsApp signup throttling
-- =============================================================================

ALTER TABLE public.volunteer_applications
  ADD COLUMN IF NOT EXISTS auth_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_parent_applications_auth_user_unique
  ON public.parent_applications (auth_user_id)
  WHERE auth_user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_volunteer_applications_auth_user_unique
  ON public.volunteer_applications (auth_user_id)
  WHERE auth_user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.signup_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_hash text NOT NULL,
  role text NOT NULL CHECK (role IN ('parent', 'teacher')),
  succeeded boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_signup_attempts_key_created
  ON public.signup_attempts (key_hash, created_at DESC);

ALTER TABLE public.signup_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.signup_attempts FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  requested_role text;
  safe_role public.user_role;
  parent_details jsonb;
  volunteer_details jsonb;
  child_ages int[] := '{}';
  volunteer_areas text[] := '{}';
BEGIN
  requested_role := COALESCE(NEW.raw_user_meta_data->>'role', 'student');
  safe_role := CASE
    WHEN requested_role IN ('student', 'teacher', 'parent')
      THEN requested_role::public.user_role
    ELSE 'student'::public.user_role
  END;

  INSERT INTO public.profiles (
    id,
    full_name,
    role,
    preferred_language,
    phone,
    is_approved
  )
  VALUES (
    NEW.id,
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'full_name', ''), NEW.email),
    safe_role,
    CASE WHEN NEW.raw_user_meta_data->>'preferred_language' = 'en' THEN 'en' ELSE 'ar' END,
    NULLIF(NEW.raw_user_meta_data->>'phone', ''),
    false
  )
  ON CONFLICT (id) DO NOTHING;

  -- Application persistence must never prevent creation of the auth account.
  BEGIN
    parent_details := NEW.raw_user_meta_data #> '{signup_details,parent}';
    IF safe_role = 'parent' AND jsonb_typeof(parent_details) = 'object' THEN
      SELECT COALESCE(array_agg(age), '{}')
      INTO child_ages
      FROM (
        SELECT value::int AS age
        FROM jsonb_array_elements_text(
          CASE
            WHEN jsonb_typeof(parent_details->'children_ages') = 'array'
              THEN parent_details->'children_ages'
            ELSE '[]'::jsonb
          END
        ) AS values_list(value)
        WHERE value ~ '^\d{1,2}$'
          AND value::int BETWEEN 3 AND 19
        LIMIT 12
      ) valid_ages;

      INSERT INTO public.parent_applications (
        auth_user_id,
        parent_name,
        profession,
        whatsapp,
        email,
        sudanese_descent,
        child_war_affected,
        missed_schooling,
        out_of_school,
        out_of_school_duration,
        out_of_school_details,
        children_count,
        children_ages,
        can_access_website,
        can_access_zoom,
        device_type,
        access_notes,
        country,
        city,
        preferred_language,
        terms_accepted_at
      )
      VALUES (
        NEW.id,
        COALESCE(NULLIF(NEW.raw_user_meta_data->>'full_name', ''), 'Parent'),
        NULLIF(parent_details->>'profession', ''),
        COALESCE(NULLIF(parent_details->>'whatsapp_number', ''), NULLIF(NEW.raw_user_meta_data->>'phone', '')),
        CASE WHEN NEW.email LIKE 'wa-%@parents.amalschool.app' THEN NULL ELSE NEW.email END,
        CASE parent_details #>> '{eligibility,sudanese_descent}' WHEN 'yes' THEN true WHEN 'no' THEN false ELSE NULL END,
        CASE parent_details #>> '{eligibility,child_affected_by_war}' WHEN 'yes' THEN true WHEN 'no' THEN false ELSE NULL END,
        CASE parent_details #>> '{eligibility,child_missed_significant_schooling}' WHEN 'yes' THEN true WHEN 'no' THEN false ELSE NULL END,
        CASE parent_details #>> '{eligibility,out_of_school}' WHEN 'yes' THEN true WHEN 'no' THEN false ELSE NULL END,
        NULLIF(parent_details #>> '{eligibility,out_of_school_duration}', ''),
        NULLIF(parent_details #>> '{eligibility,out_of_school_details}', ''),
        CASE
          WHEN parent_details->>'children_count' ~ '^\d{1,2}$'
            THEN LEAST(GREATEST((parent_details->>'children_count')::int, 1), 12)
          ELSE 1
        END,
        child_ages,
        CASE parent_details #>> '{access,can_access_website}' WHEN 'yes' THEN true WHEN 'no' THEN false ELSE NULL END,
        CASE parent_details #>> '{access,can_access_zoom}' WHEN 'yes' THEN true WHEN 'no' THEN false ELSE NULL END,
        CASE
          WHEN parent_details #>> '{access,device_type}' IN ('phone', 'tablet', 'computer', 'shared', 'none')
            THEN parent_details #>> '{access,device_type}'
          ELSE NULL
        END,
        NULLIF(parent_details #>> '{access,notes}', ''),
        NULLIF(parent_details->>'country', ''),
        NULLIF(parent_details->>'city', ''),
        CASE WHEN NEW.raw_user_meta_data->>'preferred_language' = 'en' THEN 'en' ELSE 'ar' END,
        COALESCE(NEW.created_at, now())
      )
      ON CONFLICT (auth_user_id) WHERE auth_user_id IS NOT NULL DO NOTHING;
    END IF;

    volunteer_details := NEW.raw_user_meta_data #> '{signup_details,teacher_volunteer}';
    IF safe_role = 'teacher' AND jsonb_typeof(volunteer_details) = 'object' THEN
      SELECT COALESCE(array_agg(area), '{}')
      INTO volunteer_areas
      FROM (
        SELECT value AS area
        FROM jsonb_array_elements_text(
          CASE
            WHEN jsonb_typeof(volunteer_details->'involvement_areas') = 'array'
              THEN volunteer_details->'involvement_areas'
            ELSE '[]'::jsonb
          END
        ) AS values_list(value)
        WHERE value IN ('teaching', 'tech_platform', 'content_video', 'operations', 'outreach', 'other')
      ) valid_areas;

      INSERT INTO public.volunteer_applications (
        auth_user_id,
        name,
        whatsapp,
        email,
        location_city,
        education_background,
        areas,
        hours_per_week,
        preferred_language
      )
      VALUES (
        NEW.id,
        COALESCE(NULLIF(NEW.raw_user_meta_data->>'full_name', ''), NEW.email),
        COALESCE(NULLIF(volunteer_details->>'whatsapp_number', ''), NULLIF(NEW.raw_user_meta_data->>'phone', '')),
        NEW.email,
        NULLIF(volunteer_details->>'location', ''),
        NULLIF(volunteer_details->>'educational_background', ''),
        volunteer_areas,
        NULLIF(volunteer_details->>'weekly_hours', ''),
        CASE WHEN NEW.raw_user_meta_data->>'preferred_language' = 'ar' THEN 'ar' ELSE 'en' END
      )
      ON CONFLICT (auth_user_id) WHERE auth_user_id IS NOT NULL DO NOTHING;
    END IF;
  EXCEPTION WHEN others THEN
    RAISE WARNING 'Could not persist signup application for auth user %: %', NEW.id, SQLERRM;
  END;

  RETURN NEW;
END;
$$;

-- This function is a trigger implementation, not a callable public API.
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO supabase_auth_admin;

-- Repair legacy auth users that were created while the profile trigger was
-- temporarily absent or failed. They remain unapproved for an administrator to review.
INSERT INTO public.profiles (id, full_name, role, preferred_language, phone, is_approved)
SELECT
  users.id,
  COALESCE(NULLIF(users.raw_user_meta_data->>'full_name', ''), users.email),
  CASE
    WHEN users.raw_user_meta_data->>'role' IN ('student', 'teacher', 'parent')
      THEN (users.raw_user_meta_data->>'role')::public.user_role
    ELSE 'student'::public.user_role
  END,
  CASE WHEN users.raw_user_meta_data->>'preferred_language' = 'en' THEN 'en' ELSE 'ar' END,
  NULLIF(users.raw_user_meta_data->>'phone', ''),
  false
FROM auth.users AS users
LEFT JOIN public.profiles AS profiles ON profiles.id = users.id
WHERE profiles.id IS NULL
ON CONFLICT (id) DO NOTHING;

-- Recover application records for accounts created after the expanded forms
-- launched but before application persistence was moved into the auth trigger.
INSERT INTO public.parent_applications (
  auth_user_id,
  parent_name,
  profession,
  whatsapp,
  email,
  sudanese_descent,
  child_war_affected,
  missed_schooling,
  out_of_school,
  out_of_school_duration,
  out_of_school_details,
  children_count,
  children_ages,
  can_access_website,
  can_access_zoom,
  device_type,
  access_notes,
  country,
  city,
  preferred_language,
  terms_accepted_at
)
SELECT
  users.id,
  COALESCE(NULLIF(users.raw_user_meta_data->>'full_name', ''), 'Parent'),
  NULLIF(details->>'profession', ''),
  COALESCE(NULLIF(details->>'whatsapp_number', ''), NULLIF(users.raw_user_meta_data->>'phone', ''), ''),
  CASE WHEN users.email LIKE 'wa-%@parents.amalschool.app' THEN NULL ELSE users.email END,
  CASE details #>> '{eligibility,sudanese_descent}' WHEN 'yes' THEN true WHEN 'no' THEN false ELSE NULL END,
  CASE details #>> '{eligibility,child_affected_by_war}' WHEN 'yes' THEN true WHEN 'no' THEN false ELSE NULL END,
  CASE details #>> '{eligibility,child_missed_significant_schooling}' WHEN 'yes' THEN true WHEN 'no' THEN false ELSE NULL END,
  CASE details #>> '{eligibility,out_of_school}' WHEN 'yes' THEN true WHEN 'no' THEN false ELSE NULL END,
  NULLIF(details #>> '{eligibility,out_of_school_duration}', ''),
  NULLIF(details #>> '{eligibility,out_of_school_details}', ''),
  CASE
    WHEN details->>'children_count' ~ '^\d{1,2}$'
      THEN LEAST(GREATEST((details->>'children_count')::int, 1), 12)
    ELSE 1
  END,
  ARRAY(
    SELECT age::int
    FROM jsonb_array_elements_text(
      CASE WHEN jsonb_typeof(details->'children_ages') = 'array' THEN details->'children_ages' ELSE '[]'::jsonb END
    ) AS ages(age)
    WHERE age ~ '^\d{1,2}$' AND age::int BETWEEN 3 AND 19
    LIMIT 12
  ),
  CASE details #>> '{access,can_access_website}' WHEN 'yes' THEN true WHEN 'no' THEN false ELSE NULL END,
  CASE details #>> '{access,can_access_zoom}' WHEN 'yes' THEN true WHEN 'no' THEN false ELSE NULL END,
  CASE
    WHEN details #>> '{access,device_type}' IN ('phone', 'tablet', 'computer', 'shared', 'none')
      THEN details #>> '{access,device_type}'
    ELSE NULL
  END,
  NULLIF(details #>> '{access,notes}', ''),
  NULLIF(details->>'country', ''),
  NULLIF(details->>'city', ''),
  CASE WHEN users.raw_user_meta_data->>'preferred_language' = 'en' THEN 'en' ELSE 'ar' END,
  COALESCE(users.created_at, now())
FROM auth.users AS users
CROSS JOIN LATERAL (
  SELECT users.raw_user_meta_data #> '{signup_details,parent}' AS details
) AS signup
WHERE users.raw_user_meta_data->>'role' = 'parent'
  AND jsonb_typeof(details) = 'object'
ON CONFLICT (auth_user_id) WHERE auth_user_id IS NOT NULL DO NOTHING;

INSERT INTO public.volunteer_applications (
  auth_user_id,
  name,
  whatsapp,
  email,
  location_city,
  education_background,
  areas,
  hours_per_week,
  preferred_language
)
SELECT
  users.id,
  COALESCE(NULLIF(users.raw_user_meta_data->>'full_name', ''), users.email),
  COALESCE(NULLIF(details->>'whatsapp_number', ''), NULLIF(users.raw_user_meta_data->>'phone', ''), ''),
  users.email,
  NULLIF(details->>'location', ''),
  NULLIF(details->>'educational_background', ''),
  ARRAY(
    SELECT area
    FROM jsonb_array_elements_text(
      CASE WHEN jsonb_typeof(details->'involvement_areas') = 'array' THEN details->'involvement_areas' ELSE '[]'::jsonb END
    ) AS areas(area)
    WHERE area IN ('teaching', 'tech_platform', 'content_video', 'operations', 'outreach', 'other')
  ),
  NULLIF(details->>'weekly_hours', ''),
  CASE WHEN users.raw_user_meta_data->>'preferred_language' = 'ar' THEN 'ar' ELSE 'en' END
FROM auth.users AS users
CROSS JOIN LATERAL (
  SELECT users.raw_user_meta_data #> '{signup_details,teacher_volunteer}' AS details
) AS signup
WHERE users.raw_user_meta_data->>'role' = 'teacher'
  AND jsonb_typeof(details) = 'object'
ON CONFLICT (auth_user_id) WHERE auth_user_id IS NOT NULL DO NOTHING;
