-- Keep one canonical Practice per lesson and support fully bilingual choices
-- plus cached narration generated by the server.

CREATE UNIQUE INDEX IF NOT EXISTS idx_homework_assignments_one_practice_per_lesson
  ON public.homework_assignments (lesson_id)
  WHERE is_practice = true AND lesson_id IS NOT NULL;

ALTER TABLE public.homework_questions
  ADD COLUMN IF NOT EXISTS options_ar jsonb,
  ADD COLUMN IF NOT EXISTS options_en jsonb,
  ADD COLUMN IF NOT EXISTS correct_option_index integer,
  ADD COLUMN IF NOT EXISTS audio_url_ar text,
  ADD COLUMN IF NOT EXISTS audio_url_en text,
  ADD COLUMN IF NOT EXISTS audio_text_hash_ar text,
  ADD COLUMN IF NOT EXISTS audio_text_hash_en text;

ALTER TABLE public.homework_questions
  DROP CONSTRAINT IF EXISTS homework_questions_correct_option_index_check;
ALTER TABLE public.homework_questions
  ADD CONSTRAINT homework_questions_correct_option_index_check
  CHECK (correct_option_index IS NULL OR correct_option_index BETWEEN 0 AND 5);

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'practice-audio',
  'practice-audio',
  true,
  5242880,
  ARRAY['audio/mpeg']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "Practice narration is publicly readable" ON storage.objects;
CREATE POLICY "Practice narration is publicly readable"
  ON storage.objects
  FOR SELECT
  TO public
  USING (bucket_id = 'practice-audio');
